### PR TITLE
fix: allow otp to be a number

### LINKED ISSUE #351: Schema wants OTP to be a string, but it's really a number
Providing the OTP by passing it through the CLI fails as the value provided is coerced into a number, rather than staying a string like the executor schema expects. 

```shell
>  nx run utilities:deploy-npm --otp=634119
Property 'otp' does not match the schema. '634119' should be a 'string'.
```

As a workaround, I've patched the schema to expect a number and it works just fine.

Using Nx 14.3.6 and ngx-deploy-npm 4.1.2.

### PR DESCRIPTION
**Pull request by Phault**
close #351

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] Both workspaces were tested Angular and Nx (for bug fixes/features)

## What is the current behavior?

Issue Number: #351 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dianjuar** [comment]
@Phault, I want to perform some manual operations to verify everything is going to be Ok, and then I will merge your PR.

Shortly after the merge, V4.1.5 will contain your changes.

**Comment by dianjuar** [comment]
Can you please provide examples and how we should manually test it? 

That will help us and speed your PR approval

**Comment by Phault** [comment]
I've created a basic workspace which you can use here: https://github.com/Phault/ngx-deploy-npm-repro-351, though it's really just the result of 
```shell
npx create-nx-workspace@latest my-workspace --preset=npm
cd my-workspace
npm install -D ngx-deploy-npm
nx g @nrwl/workspace:library --name my-lib --buildable --importPath my-lib
nx g ngx-deploy-npm:install
```

**Without the fix:**
`nx run mylib:deploy --dryRun --otp=123` will output:
```shell
 >  NX   Property 'otp' does not match the schema. '123' should be a 'string'.
```

`nx run mylib:deploy --dryRun --otp=abc` will output:
```shell
The options are:
{
 "access": "public",
 "otp": "abc",
 "dryRun": true,
 "noBuild": false
}
```

**With the fix:**
`nx run mylib:deploy --dryRun --otp=123` will output:
```shell
The options are:
{
 "access": "public",
 "otp": 123,
 "dryRun": true,
 "noBuild": false
}
```

`nx run mylib:deploy --dryRun --otp=abc` will output:
```shell
The options are:
{
 "access": "public",
 "otp": "abc",
 "dryRun": true,
 "noBuild": false
}
```

If you want to really make sure it works, you will of course need to enable 2fa on your npm account and do actual deployments using the OTP your authenticator generates.

**Review by dianjuar — APPROVED** [review]

**Comment by dianjuar** [comment]
Changes available on [V4.2.0](https://www.npmjs.com/package/ngx-deploy-npm/v/4.2.0)

Thank you so much for your contribution @Phault 🙌

**Pull request merged**
