### PR TITLE
ci: change default node version to 18 (#301)

### PR DESCRIPTION
**Pull request by vicmans**
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] Both workspaces were tested Angular and Nx (for bug fixes/features)

## What is the current behavior?

Change default node version in `action.yml`

Issue Number: (#301)

### CODE REVIEW

**Comment by dianjuar** [comment]
We need to wait until 25 October to integrate this PR.

In the meantime, I will update your PR using this "Update Branch" button when your branch is not up to date with master.

image

Thank you for your contribution.

**Review by dianjuar — COMMENTED** [review]
@vicmans, It's a great opportunity to update the node version for development too

On this file -> https://github.com/bikecoders/ngx-deploy-npm/blob/master/.nvmrc

**Review by dianjuar — COMMENTED** [review]
I discover another file that needs to be changed

```diff
-      - if: matrix.node-version == 16
+      - if: matrix.node-version == 18
```

https://github.com/bikecoders/ngx-deploy-npm/blob/master/.github/workflows/basic-test.yml#L56

**Comment by vicmans** [comment]
> ```diff
> matrix.node-version
> ```

Do you mean this line?: https://github.com/bikecoders/ngx-deploy-npm/blob/main/.github/workflows/basic-test.yml#L87

**Comment by dianjuar** [comment]
> > ```diff
> > matrix.node-version
> > ```
> 
> Do you mean this line?: https://github.com/bikecoders/ngx-deploy-npm/blob/main/.github/workflows/basic-test.yml#L87

Yes. A long time passed, and my link wasn't working because a new code was added.

**Comment by dianjuar** [comment]
I re-check which files should be changing, and I have listed the required ones to change node v16 to v18. I'm going to list them again:

- [.github/workflows/basic-test.yml](https://github.com/bikecoders/ngx-deploy-npm/blob/main/.github/workflows/basic-test.yml#L87)
```diff
- - if: matrix.node-version == 16 && inputs.reports == true
+ - if: matrix.node-version == 18 && inputs.reports == true
```

- [.nvmrc](https://github.com/bikecoders/ngx-deploy-npm/blob/main/.nvmrc)
```diff
- 16.18.0
+ 18
```

- [.github/actions/setup/action.yml](https://github.com/bikecoders/ngx-deploy-npm/blob/main/.github/actions/setup/action.yml#L7)
```diff
- default: '16'
+ default: '18'
```

**Review by dianjuar — APPROVED** [review]

**Comment by dianjuar** [comment]
Thank you so much for your contribution @vicmans

**Pull request merged**
